### ISSUE TITLE
RemoteFailure: portTested: http error 400: Bad Request

### ISSUE THREAD

**Issue by hyy34** [jerrymakesjelly/autoremove-torrents#101]
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.main INFO: Auto Remove Torrents 1.5.3
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.main INFO: Loading configurations...
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.task INFO: Running task 'MTeam'...
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.task INFO: Logging in...
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.task INFO: Login successfully. The client is Transmission 2.94 (d8e60ee44f).
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.task INFO: WebUI API version: 15
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.main ERROR: RemoteFailure: portTested: http error 400: Bad Request
Sat, 30 Jan 2021 03:01:07 autoremovetorrents.main ERROR: Task MTeam fails. 

为什么显示错误？？？

**Comment by livingli** [comment]
同问，一样的问题

**Comment by xyxu1024** [comment]
同问，一样的问题

**Comment by xyxu1024** [comment]
我补充一下我的配置@jerrymakesjelly
```
autoremove_autorss:
  client: Transmission
  host: http://localhost:9091
  username: admin
  password: admin
  strategies:
    ifseeding14days:
      categories:
        - AutoRSS
      status:
        - uploading
      seeding_time: 1209600
  delete_data: true
```
事实上，首次<code>autoremove-torrents -v -c config.yml</code>是能够成功运行的，输出：
```
Thu, 22 Apr 2021 23:56:06 autoremovetorrents.main INFO: Auto Remove Torrents 1.5.3
Thu, 22 Apr 2021 23:56:06 autoremovetorrents.main INFO: Loading configurations...
Thu, 22 Apr 2021 23:56:06 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Thu, 22 Apr 2021 23:56:06 autoremovetorrents.task INFO: Running task 'autoremove_autorss'...
Thu, 22 Apr 2021 23:56:06 autoremovetorrents.task INFO: Logging in...
Thu, 22 Apr 2021 23:56:06 autoremovetorrents.task INFO: Login successfully. The client is Transmission 3.00 (bb6b5a062e).
Thu, 22 Apr 2021 23:56:06 autoremovetorrents.task INFO: WebUI API version: 16
Thu, 22 Apr 2021 23:56:08 autoremovetorrents.task INFO: Status reported by the client: 
	Download Speed: 0.00B/s	Total: 0.00B
	Upload Speed: 0.00B/s	Total: 14.27GiB
	Outgoing Port Status: Open
Thu, 22 Apr 2021 23:56:08 autoremovetorrents.task INFO: Getting all the torrents...
Thu, 22 Apr 2021 23:56:09 autoremovetorrents.task INFO: Found 46 torrent(s) in the client.
```
但之后的运行就都不成功了，已经尝试了，重启transmission，问题依旧，debug输出：
```
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.main INFO: Auto Remove Torrents 1.5.3
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.main INFO: Loading configurations...
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.task DEBUG: Configuration of task 'autoremove_autorss':
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.task DEBUG: Client: Transmission, Host: http://localhost:9091, Username: admin, Password: admin
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.task DEBUG: Remove Torrents: False, Remove Torrents and Data: True
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.task DEBUG: Strategies: ifseeding14days
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.task INFO: Running task 'autoremove_autorss'...
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.task INFO: Logging in...
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.task INFO: Login successfully. The client is Transmission 3.00 (bb6b5a062e).
Fri, 23 Apr 2021 09:20:07 autoremovetorrents.task INFO: WebUI API version: 16
Fri, 23 Apr 2021 09:20:11 autoremovetorrents.main ERROR: autoremovetorrents.exception.remotefailure.RemoteFailure: portTested: http error 400: Bad Request
Fri, 23 Apr 2021 09:20:11 autoremovetorrents.main ERROR: Task autoremove_autorss fails. 
Fri, 23 Apr 2021 09:20:11 autoremovetorrents.main DEBUG: Exception Logged
Traceback (most recent call last):
  File "/home/pi/autoremove-torrents/lib/python3.7/site-packages/autoremovetorrents/main.py", line 62, in pre_processor
    Task(task_name, result[task_name], not view_mode).execute()
  File "/home/pi/autoremove-torrents/lib/python3.7/site-packages/autoremovetorrents/task.py", line 139, in execute
    self._login()
  File "/home/pi/autoremove-torrents/lib/python3.7/site-packages/autoremovetorrents/task.py", line 91, in _login
    self._client_status = self._client.client_status()
  File "/home/pi/autoremove-torrents/lib/python3.7/site-packages/autoremovetorrents/client/transmission.py", line 73, in client_status
    port_is_open = self._make_transmission_request('port-test')
  File "/home/pi/autoremove-torrents/lib/python3.7/site-packages/autoremovetorrents/client/transmission.py", line 53, in _make_transmission_request
    raise RemoteFailure(result['result'])
autoremovetorrents.exception.remotefailure.RemoteFailure: portTested: http error 400: Bad Request
```

**Comment by LaierX** [comment]
兄弟 解决了吗...我也是这样 tr3.0

**Comment by LaierX** [comment]
安装 1.5.2 版本 可以运行 不报 400 错误
但是只会删除种子,并不删除硬盘数据,(1.5.0也试了不行..其它版本没试)
需要修改和ransmission.py 中最下面 一个值为 True 才行 

这个大佬作者是弃更了吗?????

**Comment by jerrymakesjelly** [comment]
> 这个大佬作者是弃更了吗?????

没……在忙实习和秋招，有空的时候我会看一下

**Comment by livingli** [comment]
> > 这个大佬作者是弃更了吗?????
> 
> 没……在忙实习和秋招，有空的时候我会看一下

大佬，忙完了抽空测试下哦，辛苦了

**Comment by livingli** [comment]
现在是没有响应了
# autoremove-torrents --view
Sat, 27 Nov 2021 06:45:30 autoremovetorrents.main INFO: Auto Remove Torrents 1.7.1
Sat, 27 Nov 2021 06:45:30 autoremovetorrents.main INFO: Loading configurations...
Sat, 27 Nov 2021 06:45:30 autoremovetorrents.main INFO: Found 2 task(s) in the file.
Sat, 27 Nov 2021 06:45:30 autoremovetorrents.task INFO: Running task 'my_task1'...
Sat, 27 Nov 2021 06:45:30 autoremovetorrents.task INFO: Logging in...
Sat, 27 Nov 2021 06:45:30 autoremovetorrents.task INFO: Login successfully. The client is Transmission 3.00 (bb6b5a062e).
Sat, 27 Nov 2021 06:45:30 autoremovetorrents.task INFO: WebUI API version: 16
Sat, 27 Nov 2021 06:45:31 autoremovetorrents.main ERROR: autoremovetorrents.exception.remotefailure.RemoteFailure: portTested: http error 0: No Response
Sat, 27 Nov 2021 06:45:31 autoremovetorrents.main ERROR: Task my_task1 fails. 
大佬有空看下哦，感觉对tr的支持不行

**Comment by livingli** [comment]
autoremovetorrents.exception.remotefailure.RemoteFailure: portTested: http error 0: No Response

**Comment by jerrymakesjelly** [comment]
这个 portTested 的错误信息由 Transmission 产生，实际上 autoremove-torrents 已经成功请求到了 Transmission，因此我们这边暂时不会去处理此问题，建议向 Transmission 反馈。

一些细节可以去 https://github.com/jerrymakesjelly/autoremove-torrents/issues/135 查看
