### ISSUE TITLE
运行报错“”TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by lionheart2133** [jerrymakesjelly/autoremove-torrents#11]
环境是debian8，python3.4，使用的pip安装
完整日志如下:
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.main INFO: Auto Remove Torrents 1.2.4
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.main INFO: Loading configurations...
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.task INFO: Logging in...
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.task INFO: Login successfully. The client is Transmission 2.93 (0).
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.task INFO: Getting all the torrents...
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.task INFO: Found 4 seed(s) in the client.
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.strategy INFO: Running strategy trackers...
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.strategy INFO: Total: 4 seed(s). 0 seed(s) can be removed.
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.main ERROR: TypeError: argument of type 'int' is not iterable
Sat, 10 Nov 2018 19:11:06 autoremovetorrents.main ERROR: Task my_task fails. 
求解决办法。

**Comment by jerrymakesjelly** [comment]
应该是配置文件有误
