### ISSUE TITLE
是否可以关闭日志？

### ISSUE THREAD

**Issue by jiangjiangflies** [jerrymakesjelly/autoremove-torrents#122]
我仅需要测试的时候看一下日志，平时运行并不需要。希望增加关闭日志功能，仅在需要的时候自行开启。不然的话日积月累，大量的日志文件得把硬盘给弄崩了！

**Comment by eastarpen** [comment]
完全可以通过 crontab 自动删除日志

**Comment by jiangjiangflies** [comment]
> 完全可以通过 crontab 自动删除日志

可以是可以，但这就有点多此一举了，程序本身如果可以解决问题，尽量不要用外部程序干扰。

**Comment by jerrymakesjelly** [comment]
可以提供。合并至 #110。
