### ISSUE TITLE
`min_average_uploadspeed` 参数移除的新种,会被flexget反复加入任务列表吗

### ISSUE THREAD

**Issue by yeezylife** [jerrymakesjelly/autoremove-torrents#125]
我想拿新种刷上传,但有些新种出种太快我下载速度跟不上,导致上传也跟不上,于是使用了以下参数:
`min_average_uploadspeed:512` (另外这种需求是该用 `min_uploadspeed` 还是 `min_average_uploadspeed` 呢?)

但我在想如果有上传速度慢的新种被移除了,但是flexget又判断任务列表里没这个种子(然而此时这个新种还在RSS列表里),这样会不会出现反复加了删,删了加的情况啊...

**Comment by yeezylife** [comment]
还有一种情况,比如刚发出来的新种,还没人做种,这种情况也会由于没上传速度导致任务被删除吧. 
 `min_average_uploadspeed`这个参数应该排除下载进度为0的任务

**Comment by xiaoguiwk** [comment]
帮你回答一下：
1. flexget不会，想真正了解的话去flexget下面问或者看文档；
2. 要排除下载进度为0自己加个process不就好了，并不是所有参数都可以独立使用or作用的
