### ISSUE TITLE
Strategy策略统计种子数错误，seed_size可能重复占用空间

### ISSUE THREAD

**Issue by colingpt** [jerrymakesjelly/autoremove-torrents#13]
系统： Ubuntu 16.04 x64
版本： 1.2.4
配置：
```my_task:
  client: qbittorrent
  host: http://127.0.0.1:X
  username: X
  password: X
  strategies:
    s1:
      all_categories: true
      seed_size:
        limit: 1000
        action: remove-old-seeds
  delete_data: true
```
运行后输出日志：
```
x@pt:~$ autoremove-torrents --view
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.main INFO: Auto Remove Torrents 1.2.4
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.main INFO: Loading configurations...
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.task INFO: Logging in...
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v4.1.5.
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.task INFO: Getting all the torrents...
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.task INFO: Found 1 seed(s) in the client.
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.strategy INFO: Running strategy s1...
Fri, 28 Dec 2018 21:11:55 autoremovetorrents.strategy INFO: Total: 4 seed(s). 0 seed(s) can be removed.
```
此时不会删除种子，但如果有许多种子存在的时候会出现问题，例如：
```
Fri, 28 Dec 2018 20:50:16 main.py[line:38] INFO Auto Remove Torrents 1.2.4
Fri, 28 Dec 2018 20:50:16 main.py[line:40] INFO Loading configurations...
Fri, 28 Dec 2018 20:50:16 main.py[line:43] INFO Found 1 task(s) in the file.
Fri, 28 Dec 2018 20:50:16 task.py[line:74] INFO Logging in...
Fri, 28 Dec 2018 20:50:17 task.py[line:79] INFO Login successfully. The client is qBittorrent v4.1.5.
Fri, 28 Dec 2018 20:50:17 task.py[line:83] INFO Getting all the torrents...
Fri, 28 Dec 2018 20:50:17 task.py[line:93] INFO Found 16 seed(s) in the client.
Fri, 28 Dec 2018 20:50:17 strategy.py[line:74] INFO Running strategy rm-old...
Fri, 28 Dec 2018 20:50:17 strategy.py[line:83] INFO Total: 64 seed(s). 18 seed(s) can be removed.
Fri, 28 Dec 2018 20:50:17 strategy.py[line:85] INFO To be deleted:
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO 我与你的光年距离2.Long.for.You.II.2018.V2.WEB-DL.1080p.H264.AAC-HDSWEB
Size:12.78GiB	Ratio:0.795	Total Uploaded:10.17GiB	Seeding Time:0d 09:56:48	Category:HDSky
Create Time:2018-12-28 09:53:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO 我与你的光年距离2.Long.for.You.II.2018.V2.WEB-DL.1080p.H264.AAC-HDSWEB
Size:12.78GiB	Ratio:0.795	Total Uploaded:10.17GiB	Seeding Time:0d 09:56:48	Category:HDSky
Create Time:2018-12-28 09:53:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO Los.olvidados.2017.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits
Size:9.86GiB	Ratio:0.306	Total Uploaded:2.89GiB	Seeding Time:0d 07:42:53	Category:Ourbits
Create Time:2018-12-28 08:43:30
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO Los.olvidados.2017.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits
Size:9.86GiB	Ratio:0.306	Total Uploaded:2.89GiB	Seeding Time:0d 07:42:53	Category:Ourbits
Create Time:2018-12-28 08:43:30
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO Los.olvidados.2017.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits
Size:9.86GiB	Ratio:0.306	Total Uploaded:2.89GiB	Seeding Time:0d 07:42:53	Category:Ourbits
Create Time:2018-12-28 08:43:30
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO Los.olvidados.2017.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits
Size:9.86GiB	Ratio:0.306	Total Uploaded:2.89GiB	Seeding Time:0d 07:42:53	Category:Ourbits
Create Time:2018-12-28 08:43:30
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO Champion.2018.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits
Size:26.95GiB	Ratio:0.342	Total Uploaded:8.92GiB	Seeding Time:0d 06:31:58	Category:Ourbits
Create Time:2018-12-28 08:33:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO Champion.2018.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits
Size:26.95GiB	Ratio:0.342	Total Uploaded:8.92GiB	Seeding Time:0d 06:31:58	Category:Ourbits
Create Time:2018-12-28 08:33:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO Champion.2018.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits
Size:26.95GiB	Ratio:0.342	Total Uploaded:8.92GiB	Seeding Time:0d 06:31:58	Category:Ourbits
Create Time:2018-12-28 08:33:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO Champion.2018.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits
Size:26.95GiB	Ratio:0.342	Total Uploaded:8.92GiB	Seeding Time:0d 06:31:58	Category:Ourbits
Create Time:2018-12-28 08:33:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO The.Miseducation.of.Cameron.Post.2018.Blu-ray.Remux.1080p.AVC.DD.5.1-OurBits
Size:18.41GiB	Ratio:0.575	Total Uploaded:10.21GiB	Seeding Time:0d 07:02:40	Category:Ourbits
Create Time:2018-12-28 08:33:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO The.Miseducation.of.Cameron.Post.2018.Blu-ray.Remux.1080p.AVC.DD.5.1-OurBits
Size:18.41GiB	Ratio:0.575	Total Uploaded:10.21GiB	Seeding Time:0d 07:02:40	Category:Ourbits
Create Time:2018-12-28 08:33:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO The.Miseducation.of.Cameron.Post.2018.Blu-ray.Remux.1080p.AVC.DD.5.1-OurBits
Size:18.41GiB	Ratio:0.575	Total Uploaded:10.21GiB	Seeding Time:0d 07:02:40	Category:Ourbits
Create Time:2018-12-28 08:33:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO The.Miseducation.of.Cameron.Post.2018.Blu-ray.Remux.1080p.AVC.DD.5.1-OurBits
Size:18.41GiB	Ratio:0.575	Total Uploaded:10.21GiB	Seeding Time:0d 07:02:40	Category:Ourbits
Create Time:2018-12-28 08:33:28
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO 勇往直前恋上你.Shall.We.Fall.in.Love.2018.WEB-DL.1080p.H265.AAC-HDSWEB
Size:11.71GiB	Ratio:0.693	Total Uploaded:8.13GiB	Seeding Time:0d 11:11:38	Category:HDSky
Create Time:2018-12-28 08:03:23
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO 勇往直前恋上你.Shall.We.Fall.in.Love.2018.WEB-DL.1080p.H265.AAC-HDSWEB
Size:11.71GiB	Ratio:0.693	Total Uploaded:8.13GiB	Seeding Time:0d 11:11:38	Category:HDSky
Create Time:2018-12-28 08:03:23
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO 勇往直前恋上你.Shall.We.Fall.in.Love.2018.WEB-DL.1080p.H265.AAC-HDSWEB
Size:11.71GiB	Ratio:0.693	Total Uploaded:8.13GiB	Seeding Time:0d 11:11:38	Category:HDSky
Create Time:2018-12-28 08:03:23
Fri, 28 Dec 2018 20:50:17 strategy.py[line:87] INFO 勇往直前恋上你.Shall.We.Fall.in.Love.2018.WEB-DL.1080p.H265.AAC-HDSWEB
Size:11.71GiB	Ratio:0.693	Total Uploaded:8.13GiB	Seeding Time:0d 11:11:38	Category:HDSky
Create Time:2018-12-28 08:03:23
Fri, 28 Dec 2018 20:50:17 task.py[line:108] INFO The torrent 我与你的光年距离2.Long.for.You.II.2018.V2.WEB-DL.1080p.H264.AAC-HDSWEB and its data have been removed.
Fri, 28 Dec 2018 20:50:17 task.py[line:108] INFO The torrent 我与你的光年距离2.Long.for.You.II.2018.V2.WEB-DL.1080p.H264.AAC-HDSWEB and its data have been removed.
Fri, 28 Dec 2018 20:50:18 task.py[line:108] INFO The torrent Los.olvidados.2017.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent Los.olvidados.2017.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent Los.olvidados.2017.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent Los.olvidados.2017.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent Champion.2018.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent Champion.2018.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent Champion.2018.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent Champion.2018.Blu-ray.Remux.1080p.AVC.DTS-HD.MA.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent The.Miseducation.of.Cameron.Post.2018.Blu-ray.Remux.1080p.AVC.DD.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent The.Miseducation.of.Cameron.Post.2018.Blu-ray.Remux.1080p.AVC.DD.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent The.Miseducation.of.Cameron.Post.2018.Blu-ray.Remux.1080p.AVC.DD.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent The.Miseducation.of.Cameron.Post.2018.Blu-ray.Remux.1080p.AVC.DD.5.1-OurBits and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent 勇往直前恋上你.Shall.We.Fall.in.Love.2018.WEB-DL.1080p.H265.AAC-HDSWEB and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent 勇往直前恋上你.Shall.We.Fall.in.Love.2018.WEB-DL.1080p.H265.AAC-HDSWEB and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent 勇往直前恋上你.Shall.We.Fall.in.Love.2018.WEB-DL.1080p.H265.AAC-HDSWEB and its data have been removed.
Fri, 28 Dec 2018 20:50:19 task.py[line:108] INFO The torrent 勇往直前恋上你.Shall.We.Fall.in.Love.2018.WEB-DL.1080p.H265.AAC-HDSWEB and its data have been removed.
```
实际上只有16个种子存在，占用空间不到300G，但策略上认为有64个种子，应该也同时将统计的种子体积计算了4倍，并移除了多个种子？

记得使用之前版本的时候好像没有这个问题的。。。

请修复，感谢！

考研一切顺利吧？哈哈

**Comment by colingpt** [comment]
v1.1.0 测试了一下，目前正常，用一段时间看看
输出：
```
x@pt:~/autoremove-torrents-1.1.0$ cd 
x@pt:~$ autoremove-torrents --view
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: Loading configurations...
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: Found 1 task(s) in the file.
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: my_task is running.
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: Logging in...
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: Login successfully. The client is qBittorrent v4.1.5.
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: Getting all the torrents...
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: Found 1 seed(s) in the client.
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: Processing strategy s1...
Fri, 28 Dec 2018 21:27:40 autoremovetorrents.autoremove INFO: Total: 1 seed(s). 0 seed(s) can be removed.

```

**Comment by jerrymakesjelly** [comment]
应该是打印了4次日志 种子还是16个 😢

**Comment by colingpt** [comment]
> 应该是打印了4次日志 种子还是16个

但是我的种子确实被删除了，而空间只占用了300g左右，距离1000g的阀值很远的，1.10版本的现在看起来一切正常，盒子已经下载了370多个g，还没有错误删除种子，统计打印的数量也是对的

**Comment by monokoo** [comment]
最新版本也遇到了这个问题，求解啊

> Fri, 04 Jan 2019 16:13:11 autoremovetorrents.main INFO: Auto Remove Torrents 1.2.4
Fri, 04 Jan 2019 16:13:11 autoremovetorrents.main INFO: Loading configurations...
Fri, 04 Jan 2019 16:13:11 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Fri, 04 Jan 2019 16:13:11 autoremovetorrents.task INFO: Logging in...
Fri, 04 Jan 2019 16:13:11 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v4.1.5.
Fri, 04 Jan 2019 16:13:11 autoremovetorrents.task INFO: Getting all the torrents...
Fri, 04 Jan 2019 16:13:12 autoremovetorrents.task INFO: Found 6 seed(s) in the client.
Fri, 04 Jan 2019 16:13:12 autoremovetorrents.strategy INFO: Running strategy strategy_ipt...
Fri, 04 Jan 2019 16:13:12 autoremovetorrents.strategy INFO: Total: 30 seed(s). 0 seed(s) can be removed.

**Comment by monokoo** [comment]
问题已经修复了，我提了pr，可以merge下

**Comment by jerrymakesjelly** [comment]
>           问题已经修复了，我提了pr，可以merge下

感谢PR。我正在测试，如果没有问题我将合并。

**Comment by monokoo** [comment]
> > ```
> >       问题已经修复了，我提了pr，可以merge下
> > ```
> 
> 感谢PR。我正在测试，如果没有问题我将合并。

谢谢，pr里面缩进格式可能不太统一，你可以merge之后format一下

**Comment by jerrymakesjelly** [comment]
1.2.5已修复

**Comment by monokoo** [comment]
> 1.2.5已修复

你好，大佬，1.2.5还存在一点小问题，当如下配置时会触发此问题
> Sat, 12 Jan 2019 21:15:08 autoremovetorrents.main INFO: Auto Remove Torrents 1.2.5
> Sat, 12 Jan 2019 21:15:08 autoremovetorrents.main INFO: Loading configurations...
> Sat, 12 Jan 2019 21:15:08 autoremovetorrents.main INFO: Found 1 task(s) in the file.
> Sat, 12 Jan 2019 21:15:08 autoremovetorrents.task INFO: Running task 'task_mteam'...
> Sat, 12 Jan 2019 21:15:08 autoremovetorrents.task INFO: Logging in...
> Sat, 12 Jan 2019 21:15:15 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v4.1.5.
> Sat, 12 Jan 2019 21:15:15 autoremovetorrents.task INFO: Getting all the torrents...
> Sat, 12 Jan 2019 21:15:15 autoremovetorrents.task INFO: Found 16 seed(s) in the client.
> Sat, 12 Jan 2019 21:15:15 autoremovetorrents.strategy INFO: Running strategy strategy_mteam...
> Sat, 12 Jan 2019 21:15:15 autoremovetorrents.strategy INFO: Total: 16 seed(s). 0 seed(s) can be removed.
> Sat, 12 Jan 2019 21:15:15 autoremovetorrents.strategy INFO: Running strategy strategy_ipt...
> Sat, 12 Jan 2019 21:15:15 autoremovetorrents.strategy INFO: Total: 4 seed(s). 0 seed(s) can be removed.

**Comment by jerrymakesjelly** [comment]
> > 1.2.5已修复
> 
> 你好，大佬，1.2.5还存在一点小问题，只使用tracker作为筛选条件的时候会触发此问题，strategy_mteam策略是以tracker为条件，实际12个种子
> 
> > Sat, 12 Jan 2019 21:15:08 autoremovetorrents.main INFO: Auto Remove Torrents 1.2.5
> > Sat, 12 Jan 2019 21:15:08 autoremovetorrents.main INFO: Loading configurations...
> > Sat, 12 Jan 2019 21:15:08 autoremovetorrents.main INFO: Found 1 task(s) in the file.
> > Sat, 12 Jan 2019 21:15:08 autoremovetorrents.task INFO: Running task 'task_mteam'...
> > Sat, 12 Jan 2019 21:15:08 autoremovetorrents.task INFO: Logging in...
> > Sat, 12 Jan 2019 21:15:15 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v4.1.5.
> > Sat, 12 Jan 2019 21:15:15 autoremovetorrents.task INFO: Getting all the torrents...
> > Sat, 12 Jan 2019 21:15:15 autoremovetorrents.task INFO: Found 16 seed(s) in the client.
> > Sat, 12 Jan 2019 21:15:15 autoremovetorrents.strategy INFO: Running strategy strategy_mteam...
> > Sat, 12 Jan 2019 21:15:15 autoremovetorrents.strategy INFO: Total: 16 seed(s). 0 seed(s) can be removed.
> > Sat, 12 Jan 2019 21:15:15 autoremovetorrents.strategy INFO: Running strategy strategy_ipt...
> > Sat, 12 Jan 2019 21:15:15 autoremovetorrents.strategy INFO: Total: 4 seed(s). 0 seed(s) can be removed.

可以把配置文件贴上来看一下吗，方便确认问题。

**Comment by monokoo** [comment]
具体配置文件如下：
`task_mteam:
  client: qbittorrent
  host: http://127.0.0.1:2017
  username: kodi
  password: Aa-11111
  #判断模块
  strategies:
    #判断策略1
    strategy_mteam:
      #ratio: 2
      #种子存活时间
      #seeding_time: 1209600
      #all_trackers: true
      categories:
        - mteam
      ratio: 3.0
      seed_size:
        limit: 5200
        action: remove-old-seeds
    strategy_hdsky:
      categories:
        - hdsky
      seed_size:
        limit: 1000
        action: remove-old-seeds
  #是否删除数据
  delete_data: true
`

**Comment by jerrymakesjelly** [comment]
> 具体配置文件如下：
> 
> ```
> task1:
>   client: qbittorrent
>   host: http://127.0.0.1:2010
>   username: aaaa
>   password: aaaaaa
>   strategies:
>     strategy_mteaaa:
>       trackers: mteaaa.me
>       ratio: 3.0
>       seed_size:
>         limit: 5200
>         action: remove-old-seeds
>     strategy_hdskyaaa:
>       trackers: hdskyaaa.me
>       seed_size:
>         limit: 1000
>         action: remove-old-seeds
>   delete_data: true
> ```

trackers是一个列表，所以应该写成
trackers:
  - mteaaa.me
和
trackers:
  - hdskyaaa.me

**Comment by jerrymakesjelly** [comment]
> > > 具体配置文件如下：
> > > ```
> > > task1:
> > >   client: qbittorrent
> > >   host: http://127.0.0.1:2010
> > >   username: aaaa
> > >   password: aaaaaa
> > >   strategies:
> > >     strategy_mteaaa:
> > >       trackers: mteaaa.me
> > >       ratio: 3.0
> > >       seed_size:
> > >         limit: 5200
> > >         action: remove-old-seeds
> > >     strategy_hdskyaaa:
> > >       trackers: hdskyaaa.me
> > >       seed_size:
> > >         limit: 1000
> > >         action: remove-old-seeds
> > >   delete_data: true
> > > ```
> > 
> > 
> > trackers是一个列表，所以应该写成
> > ```
> > trackers:
> >   - mteaaa.me
> > ```
> > 和
> > ```
> > trackers:
> >   - hdskyaaa.me
> > ```
> 
> 多谢解答，另外种子数量多的时候，经常卡死，能看下如何提高遍历效率吗

卡死的时候程序运行到哪个阶段？是获取种子阶段还是运行策略阶段？

**Comment by monokoo** [comment]
> > > > 具体配置文件如下：
> > > > ```
> > > > task1:
> > > >   client: qbittorrent
> > > >   host: http://127.0.0.1:2010
> > > >   username: aaaa
> > > >   password: aaaaaa
> > > >   strategies:
> > > >     strategy_mteaaa:
> > > >       trackers: mteaaa.me
> > > >       ratio: 3.0
> > > >       seed_size:
> > > >         limit: 5200
> > > >         action: remove-old-seeds
> > > >     strategy_hdskyaaa:
> > > >       trackers: hdskyaaa.me
> > > >       seed_size:
> > > >         limit: 1000
> > > >         action: remove-old-seeds
> > > >   delete_data: true
> > > > ```
> > > 
> > > 
> > > trackers是一个列表，所以应该写成
> > > ```
> > > trackers:
> > >   - mteaaa.me
> > > ```
> > > 和
> > > ```
> > > trackers:
> > >   - hdskyaaa.me
> > > ```
> > 
> > 
> > 多谢解答，另外种子数量多的时候，经常卡死，能看下如何提高遍历效率吗
> 
> 卡死的时候程序运行到哪个阶段？是获取种子阶段还是运行策略阶段？

主要是两种情况卡死，一种是login时卡着不动，一个是login成功后，获取种子阶段
我之前设置的是10分钟运行一次，没想到过了一段时间系统都卡的不行，autoremve的进程大概有四五百个，只是偶尔能成功完成一次执行。与之对比的是同期flexget 能够正常login 添加下载任务。

**Comment by monokoo** [comment]
Sun, 31 Mar 2019 07:00:02 main.py[line:39] INFO Auto Remove Torrents 1.2.5
Sun, 31 Mar 2019 07:00:02 main.py[line:41] INFO Loading configurations...
Sun, 31 Mar 2019 07:00:02 main.py[line:44] INFO Found 1 task(s) in the file.
Sun, 31 Mar 2019 07:00:02 task.py[line:117] INFO Running task 'task_ipt'...
Sun, 31 Mar 2019 07:00:02 task.py[line:75] INFO Logging in...
Sun, 31 Mar 2019 07:00:02 task.py[line:80] INFO Login successfully. The client is qBittorrent v4.1.5.
Sun, 31 Mar 2019 07:00:02 task.py[line:84] INFO Getting all the torrents...
Sun, 31 Mar 2019 07:30:01 main.py[line:39] INFO Auto Remove Torrents 1.2.5
Sun, 31 Mar 2019 07:30:01 main.py[line:41] INFO Loading configurations...
Sun, 31 Mar 2019 07:30:01 main.py[line:44] INFO Found 1 task(s) in the file.
Sun, 31 Mar 2019 07:30:01 task.py[line:117] INFO Running task 'task_ipt'...
Sun, 31 Mar 2019 07:30:01 task.py[line:75] INFO Logging in...
Sun, 31 Mar 2019 07:30:01 task.py[line:80] INFO Login successfully. The client is qBittorrent v4.1.5.
Sun, 31 Mar 2019 07:30:01 task.py[line:84] INFO Getting all the torrents...
Sun, 31 Mar 2019 09:00:02 main.py[line:39] INFO Auto Remove Torrents 1.2.5
Sun, 31 Mar 2019 09:00:02 main.py[line:41] INFO Loading configurations...
Sun, 31 Mar 2019 09:00:02 main.py[line:44] INFO Found 1 task(s) in the file.
Sun, 31 Mar 2019 09:00:02 task.py[line:117] INFO Running task 'task_ipt'...
Sun, 31 Mar 2019 09:00:02 task.py[line:75] INFO Logging in...
Sun, 31 Mar 2019 09:00:02 task.py[line:80] INFO Login successfully. The client is qBittorrent v4.1.5.
Sun, 31 Mar 2019 09:00:02 task.py[line:84] INFO Getting all the torrents...
Sun, 31 Mar 2019 09:30:01 main.py[line:39] INFO Auto Remove Torrents 1.2.5
Sun, 31 Mar 2019 09:30:01 main.py[line:41] INFO Loading configurations...
Sun, 31 Mar 2019 09:30:01 main.py[line:44] INFO Found 1 task(s) in the file.
Sun, 31 Mar 2019 09:30:01 task.py[line:117] INFO Running task 'task_ipt'...
Sun, 31 Mar 2019 09:30:01 task.py[line:75] INFO Logging in...
Sun, 31 Mar 2019 09:30:01 task.py[line:80] INFO Login successfully. The client is qBittorrent v4.1.5.
Sun, 31 Mar 2019 09:30:01 task.py[line:84] INFO Getting all the torrents...
Sun, 31 Mar 2019 11:00:02 main.py[line:39] INFO Auto Remove Torrents 1.2.5
