### ISSUE TITLE
大佬请教下群辉下疑问

### ISSUE THREAD

**Issue by lee911214** [jerrymakesjelly/autoremove-torrents#142]
大佬，我想请教下我在群晖下用docker安装了art，想根据剩余空间比如小于100g来删除种子，可是日志显示找不到我给的路径，不知道咋回事？   我的群晖下绝对路径为/volume2/pt-02/downloads    映射到qb的为/downloads-1/     用这两个都提示找不到对应的路径

**Comment by lee911214** [comment]
[https://img.gejiba.com/image/EE4trS
https://img.gejiba.com/image/EE4wXT](url)

**Comment by vincent806** [comment]
1 - docker的应该使用/downloads-1而不是/volume2/pt-02/downloads
2 - 要确认映射是否成功.. 可以docker exec -it your-container-name-here /bin/sh 进入容器的命令行看/downloads-1是否可以访问

**Comment by lee911214** [comment]
> 1 - docker的应该使用/downloads-1而不是/volume2/pt-02/downloads 2 - 要确认映射是否成功.. 可以docker exec -it your-container-name-here /bin/sh 进入容器的命令行看/downloads-1是否可以访问 3 - 是不是要考虑使用remote_free_space

感谢大佬   解决了  原因是我art里面没映射文件夹。  我以为qb tr里映射就行了   我的失误
