### ISSUE TITLE
flexget和art配置后qb的webui经常崩溃

### ISSUE THREAD

**Issue by mylovesaber** [jerrymakesjelly/autoremove-torrents#17]
很感谢老哥为pt用户做出的贡献！请教个问题，我ubuntu18.04，同时安装配置了qb4.1.5-nox，flexget和你的art，参考的下面两个链接做的配置，但很频繁得出现qb的webui崩溃无法打开的情况，在链接里面看到说flexget和你的art同时允许会导致崩溃，另外新版有统计bug，不知老哥有空是否方便修复一下呢？另外请教下我现在qb的webui频繁崩溃有没有什么解决方法啊？
https://a2z.ink/qbittorrent-flexget-autoremove-torrents/

https://xerlang.github.io/2018/07/20/Seedbox%E9%83%A8%E7%BD%B2qBittorrent%E3%80%81FlexGet%E4%B8%8EAuto%20Remove%20Torrents%E5%AE%9E%E7%8E%B0%E8%B5%84%E6%BA%90%E8%87%AA%E5%8A%A8%E4%B8%8B%E8%BD%BD%E5%8F%8A%E5%88%A0%E9%99%A4%E6%95%99%E7%A8%8B/

**Comment by jerrymakesjelly** [comment]
链接中给出的配置文件都是示例，我没有办法复现这个问题，也不好确定问题的根源

希望能够把问题描述得更具体一些

**Comment by a86913179** [comment]
没有该问题，qbt-nox 4.1.6, running flexget & art in virtualenv.
