### ISSUE TITLE
如何使用win10计划任务定时运行art?

### ISSUE THREAD

**Issue by colingpt** [jerrymakesjelly/autoremove-torrents#18]
您好，linux下art已经成为必装插件了。现在想在win10下自动运行，但总是设置不好，特此求教。

在计划任务，操作，启动程序下，填写c:\users\myusername\autoremove-torrents.exe后，运行失败，提示“不是有效的win32程序”，在cmd或者powershell的相同目录下直接输入autoremove-torrent回车，可以运行成功。

请问如何设置？非常感谢！

----

更正，不知道怎么搞的。。。以前可以在cmd下运行的，现在只能在pwoershell下运行了。。。按照wiki指导的删除生成的文件，重装，还是不行。现在cmd下运行提示：
```
C:\Users\Admin>autoremove-torrents
(弹出对话框：此应用无法在此系统下运行)
Access is denied.
```
如果cmd下用powershell运行则提示如下：
```
C:\Users\Admin>powershell C:\Users\Admin\autoremove-torrents
Program 'autoremove-torrents.exe' failed to run: The specified executable is not a valid application for this OS platfo
rm.At line:1 char:1
+ C:\Users\Admin\autoremove-torrents
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ C:\Users\Admin\autoremove-torrents
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
powershell下运行则提示成功：
```
PS C:\Users\Admin> autoremove-torrents
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: Loading configurations...
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: Found 1 task(s) in the file.
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: my_task is running.
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: Logging in...
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: Login successfully. The client is qBittorrent v4.1.5.
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: Getting all the torrents...
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: Found 5 seed(s) in the client.
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: Processing strategy s1...
Sun, 13 Jan 2019 17:26:39 autoremovetorrents.autoremove INFO: Total: 5 seed(s). 0 seed(s) can be removed.
```

还请指导如何设置计划任务啊。。。

**Comment by colingpt** [comment]
已解决。

调用地址应该为完成地址，如：
```
C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\autoremove-torrents.exe
```

**Comment by jerrymakesjelly** [comment]
计划任务是Windows自带功能，自己查一下应该很好弄

**Comment by colingpt** [comment]
> 计划任务是Windows自带功能，自己查一下应该很好弄

嗯，以前没用过，python install在用户目录下生成的那个exe好诡异。。。0kb，又不想是快捷方式，像是个软连接？

**Comment by yeezylife** [comment]
@0bo 你好,请问你这样用计划任务定时运行"C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\autoremove-torrents.exe"
那config.yml文件应该放在哪啊,放在"C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\"
还是"C:\WINDOWS\system32" ?

**Comment by 0bo** [comment]
> 

放在你的自己输入的**起始于**文件夹下，当然，也可以通过**添加参数**项目来实现。具体位置就在你输入执行程序位置的下方。

**Comment by 0bo** [comment]
> @0bo 你好,请问你这样用计划任务定时运行"C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\autoremove-torrents.exe" 那config.yml文件应该放在哪啊,放在"C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts" 还是"C:\WINDOWS\system32" ?

放在你的自己输入的起始于文件夹下，当然，也可以通过添加参数项目来实现。具体位置就在你输入执行程序位置的下方。@yeezylife

**Comment by yeezylife** [comment]
> 放在你的自己输入的起始于文件夹下，当然，也可以通过添加参数项目来实现。具体位置就在你输入执行程序位置的下方。

感谢回复，我试了试直接运行`"C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\autoremove-torrents.exe"` 会闪过黑色的命令行窗口，影响其他工作。。。

**Comment by 0bo** [comment]
> > 放在你的自己输入的起始于文件夹下，当然，也可以通过添加参数项目来实现。具体位置就在你输入执行程序位置的下方。
> 
> 感谢回复，我试了试直接运行`"C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\autoremove-torrents.exe"` 会闪过黑色的命令行窗口，影响其他工作。。。

直接运行都有这个问题，如果你同时还用flexget。。。那么你会不定时弹出两个窗口，我之前在nas上用，弹就弹吧，反正也就远程接入看那么一会儿。当时也研究过，好像可以通过编写cmd脚本调用exe来实现。这个你得自己研究了哈
