### ISSUE TITLE
Complete/Paused in qbittorrent.

### ISSUE THREAD

**Issue by dnick5000** [jerrymakesjelly/autoremove-torrents#19]
I don't know if this is how it is supposed to work or not, but right now if a torrent reaches the ratio limit and is paused/completed it will not be removed by autoremove-torrents.  Is there any setting to remove the completed torrents? I was hoping to set autoremove-torrents to run once a day and remove all the completed torrents from qbittorrent.  Thanks for any help.

**Comment by jerrymakesjelly** [comment]
Yes, as you have guessed, in the ratio condition, this program only remove those torrents whose status are uploading. It's a protective setting in the early version, and I will remove It in the next version.

At the moment, this program cannot check if a torrent is completed or not, but I will add this condition in the future.
