### ISSUE TITLE
在贴吧看到的，感谢楼主的无私分享，希望能增加根据硬盘空间删种。

### ISSUE THREAD

**Issue by linanyang** [jerrymakesjelly/autoremove-torrents#2]
以前用的是transmission，找了一个脚本根据磁盘空间自动删种 http://xiaofd.win/transmission-auto-remove.html，磁盘利用率比较高。
现在用的是qbittorrent，根据你的分享设置了根据种子大小删种，可是如果同时添加多个种子且添加的种子容量比较大的话会在第一时间删掉许多做种和正在上传的种子，空出一大块空间，而不是随着下载逐渐删除。
希望能加入这个功能，非常感谢。

**Comment by jerrymakesjelly** [comment]
感谢反馈，后续会加入此功能。 😄

**Comment by linanyang** [comment]
持续关注中，谢谢！！

**Comment by Se7enMuting** [comment]
这个还是很有必要的，主要是多站都有的种子辅种，这个体积就成倍的算了.....其实占用空间只有一份....或者能识别出相同的种子，只算一份种子体积....

**Comment by chestnutxc** [comment]
webui上是有剩余空间提示的啊

> 这个还是很有必要的，主要是多站都有的种子辅种，这个体积就成倍的算了.....其实占用空间只有一份....或者能识别出相同的种子，只算一份种子体积....

**Comment by jerrymakesjelly** [comment]
感谢反馈，1.4.9已添加剩余空间删除功能
