### ISSUE TITLE
Login failure with correct login info.

### ISSUE THREAD

**Issue by soa609** [jerrymakesjelly/autoremove-torrents#20]
I'm getting login failure eventhough I'm using correct login info. My config have worked before. Login in via web browser works fine.

Fri, 18 Jan 2019 18:42:14 autoremovetorrents.main INFO: Auto Remove Torrents 1.2.5
Fri, 18 Jan 2019 18:42:14 autoremovetorrents.main INFO: Loading configurations...
Fri, 18 Jan 2019 18:42:14 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Fri, 18 Jan 2019 18:42:14 autoremovetorrents.task INFO: Running task 'my_task'...
Fri, 18 Jan 2019 18:42:14 autoremovetorrents.task INFO: Logging in...
Fri, 18 Jan 2019 18:42:14 autoremovetorrents.main ERROR: autoremovetorrents.exception.loginfailure.LoginFailure: The server returned HTTP 404.
Fri, 18 Jan 2019 18:42:14 autoremovetorrents.main ERROR: Task my_task fails.

**Comment by jerrymakesjelly** [comment]
Which version of qBittorrent are you using?

**Comment by soa609** [comment]
4.2.0alpha on ubuntu 18.04.1

**Comment by soa609** [comment]
downgrading to 4.1.5 works though! So thats what I'm doing.

**Comment by jerrymakesjelly** [comment]
It seems that qb 4.2.0 alpha stopped using the old version of the API, but the old version is still running on 4.1.5.

I'm not sure whether the old version will be deprecated in 4.2.0 or not, for compatibility, I won't fix this problem at the moment. Sorry for any inconvenience.
