### ISSUE TITLE
指定日志文件的路径

### ISSUE THREAD

**Issue by jerrymakesjelly** [jerrymakesjelly/autoremove-torrents#23]
最后问下，怎么在与config.yml同级的文件夹下做个log，把每次执行的结果都保留下来？

_Originally posted by @Se7enMuting in https://github.com/jerrymakesjelly/autoremove-torrents/issues/5#issuecomment-413835713_

**Comment by wxlg1117** [comment]
crontab添加任务加重定向到文件：
每次执行任务并且生成一个此次任务执行log文件；
*/2 * * * * /usr/local/bin/autoremove-torrents --view --conf=/data/autoremove-torrents/config.yml >>/data/art_`date +\%Y\%m\%d_\%H\%M\%S`.txt  2>&1 &

每次执行任务并且在log文件末尾追加此次任务执行log
*/2 * * * * /usr/local/bin/autoremove-torrents --view --conf=/data/autoremove-torrents/config.yml >>/data/art.txt  2>&1 &
