### ISSUE TITLE
Couldn't create autoremovetorrents.parsetab

### ISSUE THREAD

**Issue by llllevel5** [jerrymakesjelly/autoremove-torrents#32]
root@Ubuntu-1804-bionic-64-minimal ~/autoremove-torrents # autoremove-torrents
Sat, 11 May 2019 17:46:15 autoremovetorrents.main INFO: Auto Remove Torrents 1.4.1
Sat, 11 May 2019 17:46:15 autoremovetorrents.main INFO: Loading configurations...
Sat, 11 May 2019 17:46:15 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Sat, 11 May 2019 17:46:15 autoremovetorrents.task INFO: Running task 'my_task'...
Sat, 11 May 2019 17:46:15 autoremovetorrents.task INFO: Logging in...
Sat, 11 May 2019 17:46:15 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v4.1.5.
Sat, 11 May 2019 17:46:15 autoremovetorrents.task INFO: Getting all the torrents...
Sat, 11 May 2019 17:46:15 autoremovetorrents.task INFO: Found 71 torrent(s) in the client.
Sat, 11 May 2019 17:46:15 autoremovetorrents.strategy INFO: Running strategy my_strategy...
WARNING: Couldn't open 'parser.out'. [Errno 20] Not a directory: '/usr/local/lib/python3.6/dist-packages/autoremove_torrents-1.4.1-py3.6.egg/autoremovetorrents/parser.out'
Generating LALR tables
WARNING: 4 shift/reduce conflicts
WARNING: Couldn't create 'autoremovetorrents.parsetab'. [Errno 20] Not a directory: '/usr/local/lib/python3.6/dist-packages/autoremove_torrents-1.4.1-py3.6.egg/autoremovetorrents/parsetab.py'
Sat, 11 May 2019 17:46:15 autoremovetorrents.strategy INFO: Total: 50 torrent(s). 0 torrent(s) can be removed.

通过git安装，警告不影响使用，想请教这是python版本导致的问题吗？
ubuntu 18.04 64

**Comment by jerrymakesjelly** [comment]
确实是新添加的自定义表达式`remove`带来的问题。。。很抱歉，我会很快修复

**Comment by jerrymakesjelly** [comment]
1.4.2版本已修复
