### ISSUE TITLE
1.4.3已更新，感谢支持

### ISSUE THREAD

**Issue by Crazymmp** [jerrymakesjelly/autoremove-torrents#33]
1.4.3已更新，感谢支持

_Originally posted by @jerrymakesjelly in https://github.com/jerrymakesjelly/autoremove-torrents/issues/29#issuecomment-493812558_

-------
感谢大佬百忙之中抽出时间调试更新支持py2.7，我试了下V1.4.3，结果有点小问题，如下：
[root@phicomm-n1:/]# /opt/bin/autoremove-torrents --view
Mon, 20 May 2019 23:55:36 autoremovetorrents.main INFO: Auto Remove Torrents 1.4.3
Mon, 20 May 2019 23:55:36 autoremovetorrents.main INFO: Loading configurations...
Mon, 20 May 2019 23:55:36 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Running task 'my_task'...
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Logging in...
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v4.1.5.
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Getting all the torrents...
Mon, 20 May 2019 23:55:36 autoremovetorrents.task INFO: Found 0 torrent(s) in the client.
Mon, 20 May 2019 23:55:36 autoremovetorrents.strategy INFO: Running strategy s1...
Mon, 20 May 2019 23:55:36 autoremovetorrents.main ERROR: AttributeError: 'set' object has no attribute 'sort'
Mon, 20 May 2019 23:55:36 autoremovetorrents.main ERROR: Task my_task fails.
我去搜索了下这个AttributeError，说是可能是返回字符串没有成为列表啥的，就报错了，大佬您有空看看吧，我对这个还是太小白了。。。

**Comment by jerrymakesjelly** [comment]
我觉得可能是我的一个bug……可以看看您的配置文件吗（把地址和密码什么的删掉）

**Comment by Crazymmp** [comment]
大佬您看看：
my_task: 
  client: qbittorrent
  host: http://127.0.0.1:8083
  username: admin
  password: adminadmin
  strategies:
    s1:
      all_categories: true
      seeding_time: 1209600
      ratio: 1
      seed_size:
        limit: 1020
        action: remove-old-seeds
  delete_data: true

**Comment by jerrymakesjelly** [comment]
@Crazymmp 1.4.4修复了这个问题，可以确认一下

**Comment by Crazymmp** [comment]
感谢大佬神速更新，试了下V1.4.4，无任何报错，可以用了，开心！
