### ISSUE TITLE
for qbittorrent: 能不能再单独增加2个status: stalledUP&stalledDL

### ISSUE THREAD

**Issue by a86913179** [jerrymakesjelly/autoremove-torrents#34]
有些网站是用seedbox后，ratio大于一定值就不计算流量，这时候不用管是uploading还是stalledUP可以直接删除，即使用你现在定义的TorrentStatus.Uploading，但是有些网站没有限制的话就得等种子从uploading到stalledUP的状态再删除，这样能获得更多的流量，你现在放在一起的话，我如果要删除一些没有H&R的种子，都要加上做种时间的条件，因为我不知道它到底是在uploading还是stalledUP，这样有些种子如果一个小时就进入stalledUP我还要等他好久（例如我条件设置2天）才能被删除，而有些过了2天也许还在uploading，分开就很简单，只要是stalledUP的直接删除。

我尝试过修改client/qbittorrent.py的判断和添加这2个status到torrentstatus.py，但是运行的时候提示WARNING: The status 'stalledup' does not exist, so it won't be used.

我不是很懂python，只是把downloading/uploading后面的or判断去掉，重新添加一行elif判断stalledDL/stalledUP，还是麻烦你了

或者把stalledUP or stalledDL定义为inactive(stalled)，就像qbittorrent官方的web api里的filter，然后status可以使用交集，即uploading&inactive(stalled)

或者在remove的条件里设置stalleUP, 没有H&R的站点stalledUP就可以删除。有H&R的站点在用and 加个seeding time or ratio

简单来说，我的目的就是：
有限制seedbox ratio的站点：uploading or stalledUP的种子只要ratio超过网站的rules就删除
H&R：stalledUP并且ratio或者做种时间达到要求的删除
Non H&R：stalledUP直接删除

**Comment by a86913179** [comment]
#35 Why it doesn't work properly?

**Comment by jerrymakesjelly** [comment]
可以
