### ISSUE TITLE
问个低级问题，这个删除的时候是连种子带文件一起删除的吗？

### ISSUE THREAD

**Issue by weixinzhuyi** [jerrymakesjelly/autoremove-torrents#36]
这个删除的时候是连种子带文件一起删除的，还是只删除种子不清理文件？

**Comment by jerrymakesjelly** [comment]
可以在 `delete_data` 参数中指定是否同时删除文件

详见 Wiki https://github.com/jerrymakesjelly/autoremove-torrents/wiki/主页#第四部分删除数据
