### ISSUE TITLE
Feature request - remove old seed but only if last activity is more than ...

### ISSUE THREAD

**Issue by Jorman** [jerrymakesjelly/autoremove-torrents#39]
Hi, just like the tile, maybe one old torrent is in activity and one other older torrent is not in activity anymore, so is better to remove the old torrent that is no on activity.

What do you think?

**Comment by jerrymakesjelly** [comment]
Yes it will be more reasonable. 

At present whether a torrent will be removed or not only depends on the information provided by the client, but none of them provide torrents' active information, therefore we need to record it by ourselves. I will add this feature in the future, but I can't add it in a short time.

Thank you for your suggestion.

**Comment by Jorman** [comment]
Even with qBittorrent is not possible? I remember this project
https://github.com/fedarovich/qbittorrent-cli
But I don't remember if can be possible to see last activity

Thanks

**Comment by jerrymakesjelly** [comment]
> Even with qBittorrent is not possible? I remember this project
> https://github.com/fedarovich/qbittorrent-cli
> But I don't remember if can be possible to see last activity
> 
> Thanks

I found that qBittorrent will actually returns last activity field in torrent list, but the Wiki doesn't mention it. This feature will be added soon.

**Comment by Jorman** [comment]
Hi, sound's cool

Would be like
```
      seed_size:
        limit: 1000
        action: remove-old-seeds
          last_activity_min: 7 #minimum days of inactivity
```
Or what? What do you've in mind?

**Comment by jerrymakesjelly** [comment]
Yes, I will add a new action, which removes the inactive torrents (sort by the last activity field, remove the oldest active torrent from now first), just like #42 says (in Chinese).

And, another condition `last_activity` will be added, which allows user to remove those torrents which are inactive for some times.

But 
```yaml
        action: remove-old-seeds
          last_activity_min: 7 #minimum days of inactivity
```
may not be supported now, it needs an `if` expression mechanism.

**Comment by Jorman** [comment]
Ok, thanks for you work
