### ISSUE TITLE
Windows下使用报错，好像是说client名称有问题，求解

### ISSUE THREAD

**Issue by lzk800** [jerrymakesjelly/autoremove-torrents#40]
报错：
D:\>autoremove-torrents --conf=d:/autoremove-torrents/config.yml
Mon, 09 Sep 2019 10:20:14 autoremovetorrents.main INFO: Auto Remove Torrents 1.4.5
Mon, 09 Sep 2019 10:20:14 autoremovetorrents.main INFO: Loading configurations...
Mon, 09 Sep 2019 10:20:14 autoremovetorrents.main ERROR:   in "d:/autoremove-torrents/config.yml", line 2, column 9
Mon, 09 Sep 2019 10:20:14 autoremovetorrents.main CRITICAL: An error occured. If you think this is a bug or need help, you can submit an issue.

配置文件：
my_task: m-team
  client: utorrent
  host: http://127.0.0.1:8080
  username: 
  password: 
  strategies:
    strategy1: m-team
      categories: mtm
      remove: create_time > 7776000
  delete_data: true

**Comment by jerrymakesjelly** [comment]
@lzk800 配置文件有误

1. m-team应换行，然后在后面加分号
2. 注意缩进
