### ISSUE TITLE
不知道是不是utorrent支持有问题

### ISSUE THREAD

**Issue by lzk800** [jerrymakesjelly/autoremove-torrents#43]
我配置文件如下：
my_task:
  client: utorrent
  host: http://127.0.0.1:8080
  username: admin
  password: 
  strategies:
    m-team: 
      categories:
        -  mtm
      create_time: 7776000
  delete_data: true

执行结果如下：
Fri, 20 Sep 2019 10:00:57 autoremovetorrents.main INFO: Auto Remove Torrents 1.4.5
Fri, 20 Sep 2019 10:00:57 autoremovetorrents.main INFO: Loading configurations...
Fri, 20 Sep 2019 10:00:57 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Fri, 20 Sep 2019 10:00:57 autoremovetorrents.task INFO: Running task 'my_task'...
Fri, 20 Sep 2019 10:00:57 autoremovetorrents.task INFO: Logging in...
Fri, 20 Sep 2019 10:00:57 autoremovetorrents.task INFO: Login successfully. The client is uTorrent (bulid 45311).
Fri, 20 Sep 2019 10:00:58 autoremovetorrents.task INFO: Getting all the torrents...
Fri, 20 Sep 2019 10:00:59 autoremovetorrents.task INFO: Please wait...We have found 164 torrent(s).
Fri, 20 Sep 2019 10:01:00 autoremovetorrents.task INFO: Please wait...We have found 372 torrent(s).
Fri, 20 Sep 2019 10:01:01 autoremovetorrents.task INFO: Please wait...We have found 574 torrent(s).
Fri, 20 Sep 2019 10:01:01 autoremovetorrents.task INFO: Found 692 torrent(s) in the client.
Fri, 20 Sep 2019 10:01:01 autoremovetorrents.strategy INFO: Running strategy m-team...
Fri, 20 Sep 2019 10:01:01 autoremovetorrents.strategy INFO: Total: 0 torrent(s). 0 torrent(s) can be removed.

可是明明任务列表里面是有创建时间4个月的任务的

**Comment by jerrymakesjelly** [comment]
可以提供一下您的 uTorrent 版本吗，我检查一下

**Comment by lzk800** [comment]
3.55 build 45311

**Comment by jerrymakesjelly** [comment]
uTorrent不提供创建时间的数据，所以 `create_time` 在uTorrent中是无法使用的，抱歉

另外你可能还需要检查一下你的 `categories`，因为在客户端中找到了692个种子，下面运行策略的时候Total不应该为0

**Comment by lzk800** [comment]
好吧，那我切换到qBittorrent吧
