### ISSUE TITLE
qbit提示Connection aborted该如何解决

### ISSUE THREAD

**Issue by tyhunter** [jerrymakesjelly/autoremove-torrents#47]
root@debian:~/autoremove-torrents# autoremove-torrents --view --conf=/root/autoremove-torrents/config.yml
Sat, 16 Nov 2019 14:00:58 autoremovetorrents.main INFO: Auto Remove Torrents 1.4.6
Sat, 16 Nov 2019 14:00:58 autoremovetorrents.main INFO: Loading configurations...
Sat, 16 Nov 2019 14:00:58 autoremovetorrents.main INFO: Found 1 task(s) in the file.
Sat, 16 Nov 2019 14:00:58 autoremovetorrents.task INFO: Running task 'my_task'...
Sat, 16 Nov 2019 14:00:58 autoremovetorrents.task INFO: Logging in...
Sat, 16 Nov 2019 14:00:58 autoremovetorrents.task INFO: Login successfully. The client is qBittorrent v3.3.7.
Sat, 16 Nov 2019 14:00:58 autoremovetorrents.task INFO: Getting all the torrents...
Sat, 16 Nov 2019 14:00:59 autoremovetorrents.task INFO: Please wait...We have found 2 torrent(s).
Sat, 16 Nov 2019 14:01:00 autoremovetorrents.main ERROR: requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Sat, 16 Nov 2019 14:01:00 autoremovetorrents.main ERROR: Task my_task fails.

配置文件如下：
my_task:
  client: qbittorrent
  host: http://127.0.0.1:8080
  username: admin
  password: *****
  strategies:
    my_strategy:
      ratio: 1
      creat_time: 108000
      seeding_time: 86400
      seed_size:
        limitd: 700
        action: remove-old-seeds
  delete_data: true

**Comment by tyhunter** [comment]
已解决。

**Comment by oneyh** [comment]
兄弟，怎么解决的？
