### ISSUE TITLE
使用“seed_size：”参数就报错

### ISSUE THREAD

**Issue by Se7enMuting** [jerrymakesjelly/autoremove-torrents#5]
config.yml 配置如下，有缩进的，issue里不知道怎么显示缩进

my_task:
  client: transmission
  host: http://127.0.0.1:9091
  username: *
  password: *
  strategies:
    my_strategy:
      all_trackers: true
      seed_size：
        limit: 600
        action: remove-old-seeds
  delete_data: true

ssh输出结果如下：
[root@ns517928 ~]# /usr/bin/autoremove-torrents --conf=/home/autoremove-torrents/config.yml
Fri, 17 Aug 2018 18:30:08 autoremovetorrents.main INFO: Auto Remove Torrents 1.2.4
Fri, 17 Aug 2018 18:30:08 autoremovetorrents.main INFO: Loading configurations...
Fri, 17 Aug 2018 18:30:08 autoremovetorrents.main ERROR:   in "/home/autoremove-torrents/config.yml", line 12, column 3
Fri, 17 Aug 2018 18:30:08 autoremovetorrents.main CRITICAL: An error occured. Please contact the administrator for more information.

改成如下就OK：
my_task:
  client: transmission
  host: http://127.0.0.1:9091
  username: *
  password: *
  strategies:
    my_strategy:
      all_trackers: true
      seeding_time: 604800
  delete_data: true

求教seed_size和子参数应该怎么写，wiki里也没有例子~~

**Comment by Se7enMuting** [comment]
发现问题了，seed_size：limit：action：这些全是从中文wiki复制的，这些：是中文输入，应该要改成英文输出:才对。。。
还有中文wiki里例程里写的是 client: qtortorrent

**Comment by jerrymakesjelly** [comment]
>           最后问下，怎么在与config.yml同级的文件夹下做个log，把每次执行的结果都保留下来？

这个log的路径确实无法指定。。。抱歉
