### ISSUE TITLE
1.4.9安装报错

### ISSUE THREAD

**Issue by qcwolf** [jerrymakesjelly/autoremove-torrents#61]
ERROR: Could not find a version that satisfies the requirement psutil (from autoremove-torrents==1.4.9) (from versions: none)
ERROR: No matching distribution found for psutil (from autoremove-torrents==1.4.9)

**Comment by sununs** [comment]
需要安装psutil ，我的是群晖python2.7，直接先装套件python Module即可。不知道能不能帮到你

**Comment by qcwolf** [comment]
我是pythone3 安装了python Module还是不行，我去下个2.7试试。感谢大神

**Comment by qcwolf** [comment]
感谢大神，已经成功~

**Comment by sununs** [comment]
> 感谢大神，已经成功~

我不是大神，能解决就好，顺便还能减轻下作者负担。

**Comment by jerrymakesjelly** [comment]
我尝试修复了一下问题，在Python 3.3及以后的版本用 `shutil` 代替了 `psutil`，这样就不需要安装 `psutil` 了

群晖的同学可以试一下，通过拷贝仓库安装
```bash
git clone git@github.com:jerrymakesjelly/autoremove-torrents.git
cd autoremove-torrents
git checkout issue61
python3 setup.py install
```

然后就可以使用了。测试完之后可以随时通过 pip 卸载：
```bash
pip3 uninstall autoremove-torrents
```
并重新安装正式版。

期待你们的反馈

**Comment by qcwolf** [comment]
感谢大神~

> 我尝试修复了一下问题，在Python 3.3及以后的版本用 `shutil` 代替了 `psutil`，这样就不需要安装 `psutil` 了
> 
> 群晖的同学可以试一下，通过拷贝仓库安装
> 
> ```shell
> git clone git@github.com:jerrymakesjelly/autoremove-torrents.git
> cd autoremove-torrents
> git checkout issue61
> python3 setup.py install
> ```
> 
> 然后就可以使用了。测试完之后可以随时通过 pip 卸载：
> 
> ```shell
> pip3 uninstall autoremove-torrents
> ```
> 
> 并重新安装正式版。
> 
> 期待你们的反馈

感谢大神~

**Comment by jerrymakesjelly** [comment]
> 感谢大神~

不客气，没问题的话下一个版本我会把它合进主分支

**Comment by jesen2010** [comment]
> 我尝试修复了一下问题，在Python 3.3及以后的版本用 `shutil` 代替了 `psutil`，这样就不需要安装 `psutil` 了
> 
> 群晖的同学可以试一下，通过拷贝仓库安装
> 
> ```shell
> git clone git@github.com:jerrymakesjelly/autoremove-torrents.git
> cd autoremove-torrents
> git checkout issue61
> python3 setup.py install
> ```
> 
> 然后就可以使用了。测试完之后可以随时通过 pip 卸载：
> 
> ```shell
> pip3 uninstall autoremove-torrents
> ```
> 
> 并重新安装正式版。
> 
> 期待你们的反馈

root@NAS:~# git clone git@github.com:jerrymakesjelly/autoremove-torrents.git
Cloning into 'autoremove-torrents'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
这是什么问题啊？下载不下来 权限不够

**Comment by jerrymakesjelly** [comment]
> 这是什么问题啊？下载不下来 权限不够

因为你并没有本仓库的控制权，只能查看 :(

建议使用 HTTPS 方式克隆仓库
```
git clone https://github.com/jerrymakesjelly/autoremove-torrents
```
