### ISSUE TITLE
how can i do?

### ISSUE THREAD

**Issue by ceozero** [jerrymakesjelly/autoremove-torrents#64]
![image](https://user-images.githubusercontent.com/22513657/74462057-7a462880-4eca-11ea-9476-5169db2a81d5.png)

**Comment by sununs** [comment]
config文件错误。

**Comment by jerrymakesjelly** [comment]
There may be something wrong in your config file. It's likely that your config file doesn't conform the YAML file format.

To solve this problem, you can refer to [this example in documentation](https://autoremove-torrents.readthedocs.io/en/latest/config.html), or share your config file with us (but remember to hide your URL, username and password)

**Comment by ceozero** [comment]
my_task:
  client: qbittorrent
  host: http://127.0.0.1:8086
  username: 000
  password: 000
  strategies:
    strategy1:
      all_categories: true
      seeding_time: 10800
  delete_data: trues

**Comment by ceozero** [comment]
> config文件错误。

我直接复制的默认config文档测试的。这跟编码有关系吗？用哪个编码？

**Comment by sununs** [comment]
能读到my_task说明编码没问题，你这好多错误，比如seeding_time行应该是remove: seeding_time > 10800，还有应该是true不是trues。认真核对端口账号密码，仔细对照默认看看。

**Comment by sununs** [comment]
能读到my_task说明编码没问题，不过trues是什么？认真核对端口账号密码，仔细对照作者楼上发的链接看看。

**Comment by jerrymakesjelly** [comment]
@ceozero 突然想起来，详细的错误信息在日志里，所以看一下日志Traceback应该可以准确地定位问题~

如果愿意把日志贴出来就更好了

**Comment by ceozero** [comment]
`Sat, 15 Feb 2020 18:32:18 main.py[line:44] INFO Auto Remove Torrents 1.4.9
Sat, 15 Feb 2020 18:32:18 main.py[line:46] INFO Loading configurations...
Sat, 15 Feb 2020 18:32:18 main.py[line:49] INFO Found 1 task(s) in the file.
Sat, 15 Feb 2020 18:32:18 main.py[line:57] ERROR TypeError: expected string or bytes-like object
Sat, 15 Feb 2020 18:32:18 main.py[line:58] ERROR Task my_task fails. 
Sat, 15 Feb 2020 18:32:18 main.py[line:59] DEBUG Exception Logged
Traceback (most recent call last):
  File "D:\python38\lib\site-packages\autoremove_torrents-1.4.9-py3.8.egg\autoremovetorrents\main.py", line 55, in pre_processor
    Task(task_name, result[task_name], not view_mode).execute()
  File "D:\python38\lib\site-packages\autoremove_torrents-1.4.9-py3.8.egg\autoremovetorrents\task.py", line 29, in __init__
    env = pattern.match(conf[key])
TypeError: expected string or bytes-like object
`

**Comment by jerrymakesjelly** [comment]
@ceozero 抱歉，这是一个bug。。。当用户名或密码为纯数字的时候，python会把它们当作int读入而不是string，然后用int类型的变量进行正则匹配就会出现TypeError的问题

我会发一个新版解决这个bug，在此之前你可以通过在用户名和密码中加入一些字母或符号来规避这个bug

**Comment by ceozero** [comment]
`    free_space:
      all_categories: true
      excluded_categories:
        - HR
      status: uploading  
      min: 500
      path: F:\\PT
      action: remove-old-seeds
  delete_data: true`

我这个配置也不执行，是不是windows 目录编写有误？

**Comment by jerrymakesjelly** [comment]
> ` free_space: all_categories: true excluded_categories: - HR status: uploading min: 500 path: F:\\PT action: remove-old-seeds delete_data: true`

我猜你的配置文件应该是写错了，正确应该是这样

```
my_task:
  client: xxx
  host: xxx
  username: xxx
  password: xxx
  strategies:
    strategy1:
      all_categories: true
      excluded_categories:
        - HR
      status: uploading
      free_space:
        min: 500
        path: F:\\PT
        action: remove-old-seeds
  delete_data: true
```
