### ISSUE TITLE
free_space的获取问题 和HTTPS问题

### ISSUE THREAD

**Issue by zuosc** [jerrymakesjelly/autoremove-torrents#67]
翻了下源码，发现free_space是通过psutil.disk_usage获取的。

意味着这个值是通过获取当前主机指定的目录的容量？

是不是取qBittorrent 等所在的主机的目录更合适呢？

我现在是这个项目和QB 分别在两台主机上运行的。而且分别是运行在不同的容器中。
所以这个似乎就没法用了。

顺便我把autoremove-torrents运行在docker容器中。  结果报了SSL错误。我的QB是配的https.

因为对Python不熟悉，尝试修复，最后也没成功。

以上。 感谢作者的付出。

**Comment by jerrymakesjelly** [comment]
感谢反馈

> 是不是取qBittorrent 等所在的主机的目录更合适呢？
 
确实，对于两者不在同一主机的情况，free_space 就不适用了，需要添加一个新方法，比如叫 remote_free_space

目前打算借助客户端的api去获取剩余磁盘空间，你觉得如何？这样做的好处是不用填入额外的主机登录信息

> 顺便我把autoremove-torrents运行在docker容器中。 结果报了SSL错误。我的QB是配的https.

是否可以提供一下错误信息呢，比如错误代码或日志？

如果是自建的SSL证书，在使用 autoremove-torrents 时可能就会遇到问题，因为本程序目前还不允许不安全的https连接

**Comment by zuosc** [comment]
@jerrymakesjelly  

`目前打算借助客户端的api去获取剩余磁盘空间，你觉得如何？这样做的好处是不用填入额外的主机登录信息`

我觉得非常好。

`是否可以提供一下错误信息呢，比如错误代码或日志？`
不是使用的自建HTTPS证书。 是使用的Let's Encrypt Authority X3证书。

应该不是你代码的问题，而是docker 镜像python:3.7.6-alpine的问题。我本地运行是没问题的，进入到容器里就出错。报的错误也很直白，就是本地证书错误。

**Comment by zuosc** [comment]
@jerrymakesjelly 

顺带提一个小建议。。。。

可以考虑把文档的`最后一步……`  提到最开始。。。。

像我这种急性子，一下子3个T的做种就被我删除到只剩50G。。

原因估计你也猜到了，是哪里配错了。。

**Comment by husx** [comment]
我也有同样的问题，qb部署在容器，主机安装autoremove-torrents，使用free_space条件时日志一直说没符合条件的种子

**Comment by lhllhx** [comment]
我是直接安装的 qb4.2.5 用的是亚洲诚信的证书 但是还是出现ssl错误
