### ISSUE TITLE
excluded_categories和status能否共存 & categories是否支持中文

### ISSUE THREAD

**Issue by Latezly** [jerrymakesjelly/autoremove-torrents#69]
我在flexget上对针对站点不同添加了不同的分类
![$Y0ZI D`Z$WVH5DS1SE0VBT](https://user-images.githubusercontent.com/17759624/76791268-73794100-67fb-11ea-960f-5a0e5e047cdc.png)
其中有一些站点有全站H&R，我想把处于做种状态且不属于全站H&R的种子删除，尝试了两种方法

1.排除指定的分类且正处于做种状态的种子
![8(D{VYL6C
TJT4MJM_ YWE](https://user-images.githubusercontent.com/17759624/76791961-eb943680-67fc-11ea-9824-3ec913699ee7.png)
结果是第一个排除过滤器完全没生效，autoremove-torrents --view后还是把TL和IPT标签的种子列了出来
2.指定非H&R标记的标签种子且正处于做种状态的种子
![PQ{)S09ZQD}~19M(_O60GMC](https://user-images.githubusercontent.com/17759624/76792145-52b1eb00-67fd-11ea-9b9e-0088b81c8afa.png)
结果autoremove-torrents --view一个种子都没有列出来

ubuntu18.04
Python 3.6.9
qbittorrent4.2.1

**Comment by jerrymakesjelly** [comment]
> 1.排除指定的分类且正处于做种状态的种子
> ![8(D{VYL6C TJT4MJM_ YWE](https://user-images.githubusercontent.com/17759624/76791961-eb943680-67fc-11ea-9824-3ec913699ee7.png)
> 结果是第一个排除过滤器完全没生效，autoremove-torrents --view后还是把TL和IPT标签的种子列了出来

excluded_categories与status可以共存
按照YAML的语法，横杠 ``-`` 与后面的文字之间需要用一个空格隔开，否则这个列表可能会被误认为是字符串

> 2.指定非H&R标记的标签种子且正处于做种状态的种子
> ![PQ{)S09ZQD}~19M(_O60GMC](https://user-images.githubusercontent.com/17759624/76792145-52b1eb00-67fd-11ea-9b9e-0088b81c8afa.png)
> 结果autoremove-torrents --view一个种子都没有列出来

抱歉，这确实是一个中文支持的bug，我会在下一个版本修复
感谢您的反馈
