### ISSUE TITLE
请问一下remove-inactive-seeds是如何定义的？

### ISSUE THREAD

**Issue by FduJyy** [jerrymakesjelly/autoremove-torrents#72]
如果我所有种子当前都在上传下载，remove-inactive-seeds会根据什么来选择要删除的种子？

**Comment by jerrymakesjelly** [comment]
remove-inactive-seeds 并非通过种子 **是否** 正在活跃来判断能否删除，而是将种子的最后活动时间从远到近排列，优先删除最后活动时间较远的种子
