### ISSUE TITLE
请求处理别个删种关键词

### ISSUE THREAD

**Issue by mylovesaber** [jerrymakesjelly/autoremove-torrents#79]
>max_progress

autoremovetorrents.main ERROR: NoSuchCondition: The condition 'max_progress' is not supported.

qb和de均不支持。不知道可否修复

请求增加 **下载量** 和 **上传量** 关键词
感谢老哥的辛勤付出

**Comment by jerrymakesjelly** [comment]
> max_progress

> autoremovetorrents.main ERROR: NoSuchCondition: The condition 'max_progress' is not supported.

> qb和de均不支持。不知道可否修复

`remove`  方式里面使用 `progress` 关键词即可

**Comment by mylovesaber** [comment]
请求增加运行程序时读取 **当前上传速度** 和 **当前下载速度** 这两个关键词，是读取时的瞬时值，不是平均值，不知道可否实现
