### ISSUE TITLE
希望尽快增加对deluge的支持

### ISSUE THREAD

**Issue by cdyehl** [jerrymakesjelly/autoremove-torrents#8]
希望尽快增加对deluge的支持，我的系统是用群晖DS3617，群晖套件中心里面的deluge是需要Python2.7，能将下个版本同时支持Python2.7和Python3.5吗？

**Comment by jerrymakesjelly** [comment]
好的，没问题，对Deluge的支持一直都在本项目的计划列表中。

最近我在准备研究生考试，所以等要到12月底我才能对这个项目进行更新。谢谢支持，希望你能等一等，抱歉。

**Comment by jerrymakesjelly** [comment]
官方将于今年年底停止对Python 2.7提供支持，因此本程序不会再去适配Python 2.7，感谢理解

https://pythonclock.org/

**Comment by a86913179** [comment]
deluge有自己的插件Auto Remove Plus，没必要做重复的工作
