### ISSUE TITLE
IncompatibleAPIversion for qbittorent client for qBittorrent v4.2.1 Web UI (64-bit)

### ISSUE THREAD

**Issue by ihaddy** [jerrymakesjelly/autoremove-torrents#81]
Just found the program, read through the docs to use it and thought i saw compatibility was added for qbittorrent v4.2.1 but when i install and run the latest 1.5.2 of auto remove torrents, i get this error without much more info.
### config file
```
my_task:        
  client: qbittorrent
  host: http://192.168.1.168:8080/
  username: admin
  password: SaGb2aX2K9guxI4wGCH#frz7GzF^YL 
  strategies:
    strategy1:    # Part I: Strategy Name
       Part II: Filters
      status:
        - StalledDownload
       Part III: Remove Condition
      last_activity: 15
  delete_data: true
```
### output from powershell

running autoremove-torrents -c pathtoconfigfile -v yields

> Sat, 08 Aug 2020 16:32:43 autoremovetorrents.main INFO: Auto Remove Torrents 1.5.2
> Sat, 08 Aug 2020 16:32:43 autoremovetorrents.main INFO: Loading configurations...
> Sat, 08 Aug 2020 16:32:43 autoremovetorrents.main INFO: Found 1 task(s) in the file.
> Sat, 08 Aug 2020 16:32:43 autoremovetorrents.task INFO: Running task 'my_task'...
> Sat, 08 Aug 2020 16:32:43 autoremovetorrents.main ERROR: IncompatibleAPIVersion: Incompatible qbittorrent client. The cu
> rrent API version may be unsupported.
> Sat, 08 Aug 2020 16:32:43 autoremovetorrents.main ERROR: Task my_task fails.

**Comment by jerrymakesjelly** [comment]
> host: http://192.168.1.168:8080/

It's a bug, and you can solve this by removing the / at the end of the host URL.

Sorry for any inconvenience.

**Comment by jesen2010** [comment]
我也遇到同样的问题，删种版本1.5.2，qb是4.2.5，之前都工作好好的，突然就报这个不兼容的错误，我的配置文件host末尾没有/  这个怎么弄呢？
