### ISSUE TITLE
【建议】希望添加删种前限速的功能还有能设置判断可用空间的行为在获取种子信息前面

### ISSUE THREAD

**Issue by kafuuchino-s** [jerrymakesjelly/autoremove-torrents#85]
我有3000多个种，使用的是剩余空间的条件来判断删种，每次都需要先扫描3000多个种子信息才能进行判断，不知道可以将判断可用空间的条件放到前面，如果还有空间就不用在继续后面的扫描了。至于删种前限速是因为，我的qb容易跑满1000M，不限速的话，删种程序直接卡死在webui的获取种子信息上，qb也未响应。

**Comment by RednaxelaAXX** [comment]
是的是的，这个功能急求，先判断剩余空间，再选择分类、状态之类的，然后再有remove那些就好了，谢谢

**Comment by mylovesaber** [comment]
你的思路就是错的，既然是保种为何要自动删种？刷流才需要删种，保种就是纯粹的保种，建议别放一个客户端里面，qb这种两千种都卡得没法用了你三千种还删呢？

**Comment by kafuuchino-s** [comment]
我3000种都是小种，用起来只要上传速度没到50m/s以上就不会卡，删种也正常删，就是每次删种之前要扫描较长一段时间，才进行剩余空间判断，然后空间足够，不用删。这样的话，中间就浪费了一段时间。所以我觉得可以把空间判断放前面，我有保种，有刷流，qb多开容易出问题。总之我的思路就是同一个客户端，我就是既有保种也有刷流，我自己简单的用psutil来先判断空间，空间不够了才运行autoremove-torrents来扫描删种，5分钟一次，就节省了扫描时间。

**Comment by kafuuchino-s** [comment]
> 你的思路就是错的，既然是保种为何要自动删种？刷流才需要删种，保种就是纯粹的保种，建议别放一个客户端里面，qb这种两千种都卡得没法用了你三千种还删呢？

我3000种都是小种，用起来只要上传速度没到50m/s以上就不会卡，删种也正常删，就是每次删种之前要扫描较长一段时间，才进行剩余空间判断，然后空间足够，不用删。这样的话，中间就浪费了一段时间。所以我觉得可以把空间判断放前面，我有保种，有刷流，qb多开容易出问题。总之我的思路就是同一个客户端，我就是既有保种也有刷流，我自己简单的用psutil来先判断空间，空间不够了才运行autoremove-torrents来扫描删种，5分钟一次，就节省了扫描时间。

**Comment by jerrymakesjelly** [comment]
好的，后续加入的 `if` 表达式可以满足先判断再工作的需求

另外ART也有计划降低请求的数量和参数量，以缓解客户端的压力
