### ISSUE TITLE
Clarification about some parameters

### ISSUE THREAD

**Issue by dantebarba** [jerrymakesjelly/autoremove-torrents#86]
I'm looking to use autoremove-torrents for a personal project. Basically I need to remove a torrent if the download speed is too slow for more than X amount of time, only if the status of the torrent is downloading. 

After reading the docs, I have some doubts about how these parameters are measured:

**max_average_downloadspeed:** How is it calculated?. If the torrent is paused, will it show an average of 0?. How much time does it wait to compute an average?. As a torrent starts to download, the average will generally be low, as it takes time to reach all the seeders available. This would result in unreliable results when scanning to autoremove.

**create_time** In which point does it start to measure creation time. When the torrent is added? When it's ready for download?.

**seeding_time** Same as above. When does it start to measure time?.

Thanks

**Comment by jerrymakesjelly** [comment]
Thanks. It's a good question.

Actually, these parameters **are not** calculated by autoremove-torrents, and they are simply fetched via the APIs of your client. So, if you want to know how these parameters are measured, you may need to check the documentations of your client or find the answer from your client's source code.

For example, assume the autoremove-torrents works with qBittorrent. So the `average_downloadspeed` refers to the `dl_speed_avg` in qBittorrent's WebAPI, and the `dl_speed_avg` is measured as

https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/api/torrentscontroller.cpp#L414
```c++
const qlonglong dlDuration = torrent->activeTime() - torrent->finishedTime();
dataDict[KEY_PROP_DL_SPEED_AVG] = torrent->totalDownload() / ((dlDuration == 0) ? -1 : dlDuration);
```

So in qBittorrent, it's just downloaded size divides by downloading time. It may not be 0 when it's paused. And it's measured from the downloading starts.

The `create_time` refers to the `addition_date`, which refers to the `added_time` in libtorrent.

https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/api/torrentscontroller.cpp#L433
```c++
dataDict[KEY_PROP_ADDITION_DATE] = static_cast<double>(torrent->addedTime().toSecsSinceEpoch());
```

And it's defined in https://www.libtorrent.org/reference-Torrent_Status.html#torrent_status.

> added_time
> the posix-time when this torrent was added. i.e. what time(nullptr) returned at the time.

The `seeding_time` refers to the `seeding_time` in qBittorrent, which refers to the `finished_duration` in libtorrent.

https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/api/torrentscontroller.cpp#L404
```c++
dataDict[KEY_PROP_SEEDING_TIME] = torrent->finishedTime();
```

In libtorrent's document, the `finished_duration` is

https://www.libtorrent.org/reference-Torrent_Status.html#torrent_status
> finished means all selected files/pieces were downloaded and available to other peers (this is always a subset of active time).
