### ISSUE TITLE
您好，想请问下能不能删除一段时间内未完成的种子？

### ISSUE THREAD

**Issue by philboycn** [jerrymakesjelly/autoremove-torrents#87]
看了半天不知道有没有这个功能。比如我想实现开始下载8小时以后还没完成的种子，能行吗？

**Comment by dantebarba** [comment]
+1 here. I need the same feature. There is a parameter in Transmission called Running Time. It specifies the amount of time the torrent is in the downloading status. I guess I'll fork it and add it myself

**Comment by dantebarba** [comment]
It's already parsed, at least for Transmission: 

https://github.com/jerrymakesjelly/autoremove-torrents/blob/cf799d5fe22a1fdacc7ffd76c869e42c12c1f9f4/autoremovetorrents/client/transmission.py#L129

**Comment by RednaxelaAXX** [comment]
> 
> 
> 看了半天不知道有没有这个功能。比如我想实现开始下载8小时以后还没完成的种子，能行吗？

兄弟，这个功能有了，你用创建时间作为条件就行了

**Comment by philboycn** [comment]
> > 看了半天不知道有没有这个功能。比如我想实现开始下载8小时以后还没完成的种子，能行吗？
> 
> 兄弟，这个功能有了，你用创建时间作为条件就行了

可是已完成的种子不想删除啊，只想删除8小时内未完成的种子。

**Comment by dantebarba** [comment]
> > 看了半天不知道有没有这个功能。比如我想实现开始下载8小时以后还没完成的种子，能行吗？
> 
> 兄弟，这个功能有了，你用创建时间作为条件就行了

Creation time includes queue time. I've already added a branch with qbt and transmission support for downloading time parameter.

**Comment by RednaxelaAXX** [comment]
> > > 看了半天不知道有没有这个功能。比如我想实现开始下载8小时以后还没完成的种子，能行吗？
> > 
> > 
> > 兄弟，这个功能有了，你用创建时间作为条件就行了
> 
> 可是已完成的种子不想删除啊，只想删除8小时内未完成的种子。

可以的，用remove，下载进度小于100，创建时间大于8小时就行了

**Comment by philboycn** [comment]
> > > > 看了半天不知道有没有这个功能。比如我想实现开始下载8小时以后还没完成的种子，能行吗？
> > > 
> > > 
> > > 兄弟，这个功能有了，你用创建时间作为条件就行了
> > 
> > 
> > 可是已完成的种子不想删除啊，只想删除8小时内未完成的种子。
> 
> 可以的，用remove，下载进度小于100，创建时间大于8小时就行了

感谢兄弟，已搞定！！结帖。

**Comment by philboycn** [comment]
> > > 看了半天不知道有没有这个功能。比如我想实现开始下载8小时以后还没完成的种子，能行吗？
> > 
> > 
> > 兄弟，这个功能有了，你用创建时间作为条件就行了
> 
> Creation time includes queue time. I've already added a branch with qbt and transmission support for downloading time parameter.

Thanks for your docker container. it works like a charm !
