### ISSUE TITLE
辅种问题

### ISSUE THREAD

**Issue by zuosc** [jerrymakesjelly/autoremove-torrents#98]
平时利用了一个自动辅种工具-->  https://github.com/ledccn/IYUUAutoReseed

目前有这样的问题，校验数据+做种的时候，最后活动时间都是1970-01-01 08:00:00 

我的删除策略是：
```
remove: last_activity > 864000
```

然后这就尴尬了。。。经常导致辅种的种子自动被删除。。。

相关问题：
https://github.com/jerrymakesjelly/autoremove-torrents/issues/89

**Comment by jerrymakesjelly** [comment]
我会修复这个问题，从未活跃过的种子将不再触发 `last_activity` 删除条件

**Comment by jerrymakesjelly** [comment]
1.5.4 版本已发布，因此关闭此 issue。
